# ---------------------------------
# GitHub Actions - Basic Pipeline
#
# Copyleft (c) Aleksandr Rogembaum
# ---------------------------------

name: GitHub-Actions-Basics
on:
  push:
    branches: 
      - master
env   :
  POWERSHELL_VERSION: $PSVersionTable.PSVersion  

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Testing job" 
  
  
  my-deploy:
    needs  : [my-testing] 
    runs-on: ubuntu-latest
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Deploy job" 
  

  my-prod:
    needs  : [my-deploy]
    runs-on: windows-latest 
    
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Deploy job"
        
      - name: Print Ipconfig Message
        run : ipconfig /all 
      
      
      - name: Print Powershell Version Message
        run : $ {{ env.POWERSHELL_VERSION }}
        
