# ---------------------------------
# GitHub Actions - Basic Pipeline
#
# Copyleft (c) Aleksandr Rogembaum
# ---------------------------------

name: GitHub-Actions-Basics
env   :
  POWERSHELL_VERSION  : "(Get-Variable PSVersionTable -ValueOnly).PSVersion"
  DEPLOY_PACKAGE_NAME : "flask-deploy-ver- ${{ github.sha }}" 

on:
  push:
    branches: 
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Testing job" 
      
        
  my-deploy:
    needs  : [my-testing] 
    runs-on: ubuntu-latest
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Deploy job" 
  
      - name : Print Deploy Package name
        run  : echo "Deploy packege name is ${{ env.DEPLOY_PACKAGE_NAME }}" 
  
  my-prod:
    needs  : [my-deploy]
    runs-on: windows-latest 
    
    steps  :
      - name: Print Hello World Message
        run : echo "Hello World from Deploy job"
        
      - name: Print Ipconfig Message
        run : ipconfig /all 
      
      
      - name: Print Powershell Version Message
        run : powershell -command ${{ env.POWERSHELL_VERSION }}
      
